name: Build

on :
  schedule:
  - cron: "5 0 * * 0"
  workflow_dispatch:
  push:
     branches:
      - main/Genshin
      

jobs:
 build: 
   runs-on: windows-latest
   
   steps:
     - name: test
       run: |
           tsc
           
     
